- name: set prompt as grafana
  ansible.builtin.shell: set-prompt grafana

- name: Template grafana.repo file to /etc/yum.repos.d/
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: Start service grafana, if not started
  ansible.builtin.service:
    name: grafana
    state: started
    enabled: yes
