- name: set prompt as grafana
  ansible.builtin.shell: set-prompt grafana

- name: Template grafana.repo file to /etc/yum.repos.d/
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: Copy Datasource
  ansible.builtin.template:
    src: prom-datasource.yml
    dest: /etc/grafana/provisioning/datasources/prom.yml

- name: Create a folder
  community.grafana.grafana_folder:
    url: http://localhost:3000
    grafana_user: "{{secrets.grafana_user}}"
    grafana_password: "{{secrets.grafana_password}}"
    title: "ProjectDashboards"
    state: present

- name: Include task list in play
  ansible.builtin.include_tasks:
    file: import-dashboard.yml
  loop:
    - node-exporter
    - caddy

- name: Start service grafana, if not started
  ansible.builtin.service:
    name: grafana-server
    state: restarted
    enabled: yes
