- name: adding hashicorp repo
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -y

- name: install vault package
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: start the service
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true