- name: setting up prompt
  ansible.builtin.shell: set-prompt prometheus

- name: Un-archive file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: bin

- name: copy prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: copy prometheus template file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.50.1.linux-amd64/prometheus.yml

- name: Start Prometheus Service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes